--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/LegendOfMCPE/Hormones
projects:
  Hormones-Latest:
    path: Hormones/
    stub: stubs/entry.php
    includeDirs:
      stubs: =
    includeFiles:
      /phagocyte.php: stubs/phagocyte.php
    icon: hormones.png

    libs:
      - src: poggit/libasynql/libasynql
        version: ^1.3
      - src: Falkirks/spoondetector/spoondetector
        version: ^0

  NetChat:
    path: NetChat

    libs:
      - src: poggit/libasynql/libasynql
        version: ^1.3
...
